# Generated by Django 4.1.3 on 2023-01-18 06:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default=0, max_length=128, region='RU', verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
