# Generated by Django 4.1 on 2023-01-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop', '0002_order_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowersbunch',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Картинка букета'),
        ),
    ]
